BEGIN;
-- Preenche somente imagens ausentes, preservando URLs configuradas anteriormente.
-- DAPI: https://digi-api.com/ e https://digi-api.com/api/v1/digimon?name=...
-- Wikimon: https://wikimon.net/ (somente correspondências específicas não encontradas na DAPI).
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Agumon.png' WHERE name = 'Agumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://wikimon.net/images/0/00/Algomon_baby1.jpg' WHERE name = 'Algomon Baby I' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Birdramon.png' WHERE name = 'Birdramon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Bombmon.png' WHERE name = 'Bombmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Bommon.png' WHERE name = 'Bommon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Botamon.png' WHERE name = 'Botamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Bubbmon.png' WHERE name = 'Bubbmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Chibickmon.png' WHERE name = 'Chibickmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Chicomon.png' WHERE name = 'Chicomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Choromon.png' WHERE name = 'Choromon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Cocomon.png' WHERE name = 'Cocomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Cotsucomon.png' WHERE name = 'Cotsucomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Curimon.png' WHERE name = 'Curimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Dodomon.png' WHERE name = 'Dodomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Dokimon.png' WHERE name = 'Dokimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Fufumon.png' WHERE name = 'Fufumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://wikimon.net/images/7/78/Fukamon.jpg' WHERE name = 'Fukamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Fusamon.png' WHERE name = 'Fusamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Gabumon.png' WHERE name = 'Gabumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Garurumon.png' WHERE name = 'Garurumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Gomamon.png' WHERE name = 'Gomamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Greymon.png' WHERE name = 'Greymon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Ikkakumon.png' WHERE name = 'Ikkakumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Jyarimon.png' WHERE name = 'Jyarimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Kabuterimon.png' WHERE name = 'Kabuterimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Keemon.png' WHERE name = 'Keemon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://wikimon.net/images/9/9c/Kekomon.jpg' WHERE name = 'Kekomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Ketomon.png' WHERE name = 'Ketomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Koromon.png' WHERE name = 'Koromon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Kuramon.png' WHERE name = 'Kuramon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Leafmon.png' WHERE name = 'Leafmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Mokumon.png' WHERE name = 'Mokumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Nyokimon.png' WHERE name = 'Nyokimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Pafumon.png' WHERE name = 'Pafumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Paomon.png' WHERE name = 'Paomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Patamon.png' WHERE name = 'Patamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Peti_Meramon.png' WHERE name = 'Peti Meramon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Petitmon.png' WHERE name = 'Petitmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Pipimon.png' WHERE name = 'Pipimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Pitchmon.png' WHERE name = 'Pitchmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Popomon.png' WHERE name = 'Popomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Poyomon.png' WHERE name = 'Poyomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Punimon.png' WHERE name = 'Punimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Pupumon.png' WHERE name = 'Pupumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Pururumon.png' WHERE name = 'Pururumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Pusumon.png' WHERE name = 'Pusumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Puttimon.png' WHERE name = 'Puttimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Puwamon.png' WHERE name = 'Puwamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Puyomon.png' WHERE name = 'Puyomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Pyonmon.png' WHERE name = 'Pyonmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Relemon.png' WHERE name = 'Relemon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Sakumon.png' WHERE name = 'Sakumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Sunamon.png' WHERE name = 'Sunamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Tentomon.png' WHERE name = 'Tentomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Tokomon.png' WHERE name = 'Tokomon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://wikimon.net/images/e/e5/Tomorimon.jpg' WHERE name = 'Tomorimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Torikara_Ballmon.png' WHERE name = 'Torikara Ballmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Tsubumon.png' WHERE name = 'Tsubumon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Yolkmon.png' WHERE name = 'Yolkmon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Yukimi_Botamon.png' WHERE name = 'Yukimi Botamon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Yuramon.png' WHERE name = 'Yuramon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Zerimon.png' WHERE name = 'Zerimon' AND (image_url IS NULL OR btrim(image_url) = '');
UPDATE digimon_infos SET image_url = 'https://digi-api.com/images/digimon/w/Zurumon.png' WHERE name = 'Zurumon' AND (image_url IS NULL OR btrim(image_url) = '');
COMMIT;
