ALTER TABLE digimons
ADD COLUMN bits INTEGER NOT NULL DEFAULT 0;

ALTER TABLE digimons
ADD COLUMN rebirth_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE digimons
ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';