INSERT INTO evolution_line_steps (evolution_line_id, digimon_info_id, stage, step_order, required_level)
SELECT line.id, info.id, data.stage, data.step_order,
       CASE data.step_order
           WHEN 1 THEN 1
           WHEN 2 THEN 10
           WHEN 3 THEN 15
           WHEN 4 THEN 25
           WHEN 5 THEN 50
           WHEN 6 THEN 75
           ELSE 1
       END
FROM (
    VALUES
    ('ALGOMON_LINE_1', 1, 'Algomon Baby I', 'BABY'),
    ('ALGOMON_LINE_1', 2, 'Algomon (Baby II)', 'BABY_II'),
    ('ALGOMON_LINE_1', 3, 'Algomon (Child)', 'ROOKIE'),
    ('ALGOMON_LINE_1', 4, 'Algomon (Adult)', 'CHAMPION'),
    ('ALGOMON_LINE_1', 5, 'Algomon (Perfect)', 'ULTIMATE'),
    ('ALGOMON_LINE_1', 6, 'Algomon (Ultimate)', 'MEGA'),
    ('BOMBMON_LINE_1', 1, 'Bombmon', 'BABY'),
    ('BOMBMON_LINE_1', 2, 'Missimon', 'BABY_II'),
    ('BOMBMON_LINE_1', 3, 'Commandramon', 'ROOKIE'),
    ('BOMBMON_LINE_1', 4, 'Sealsdramon', 'CHAMPION'),
    ('BOMBMON_LINE_1', 5, 'Tankdramon', 'ULTIMATE'),
    ('BOMBMON_LINE_1', 6, 'Darkdramon', 'MEGA'),
    ('BOMMON_LINE_1', 1, 'Bommon', 'BABY'),
    ('BOMMON_LINE_1', 2, 'Kapurimon', 'BABY_II'),
    ('BOMMON_LINE_1', 3, 'Impmon', 'ROOKIE'),
    ('BOMMON_LINE_1', 4, 'Bakemon', 'CHAMPION'),
    ('BOMMON_LINE_1', 5, 'Myotismon', 'ULTIMATE'),
    ('BOMMON_LINE_1', 6, 'Beelzebumon', 'MEGA'),
    ('BUBBMON_LINE_1', 1, 'Bubbmon', 'BABY'),
    ('BUBBMON_LINE_1', 2, 'Mochimon', 'BABY_II'),
    ('BUBBMON_LINE_1', 3, 'Otamamon', 'ROOKIE'),
    ('BUBBMON_LINE_1', 4, 'Gekomon', 'CHAMPION'),
    ('BUBBMON_LINE_1', 5, 'ShogunGekomon', 'ULTIMATE'),
    ('BUBBMON_LINE_1', 6, 'MarineAngemon', 'MEGA'),
    ('CHIBICKMON_LINE_1', 1, 'Chibickmon', 'BABY'),
    ('CHIBICKMON_LINE_1', 2, 'Pickmon', 'BABY_II'),
    ('CHIBICKMON_LINE_1', 3, 'Starmons', 'ROOKIE'),
    ('CHIBICKMON_LINE_1', 4, 'Shoutmon', 'CHAMPION'),
    ('CHIBICKMON_LINE_1', 5, 'OmegaShoutmon', 'ULTIMATE'),
    ('CHIBICKMON_LINE_1', 6, 'Shoutmon X7 (Superior Mode)', 'MEGA'),
    ('CHOROMON_LINE_1', 1, 'Choromon', 'BABY'),
    ('CHOROMON_LINE_1', 2, 'Pagumon', 'BABY_II'),
    ('CHOROMON_LINE_1', 3, 'Gazimon', 'ROOKIE'),
    ('CHOROMON_LINE_1', 4, 'Devidramon', 'CHAMPION'),
    ('CHOROMON_LINE_1', 5, 'Cyberdramon', 'ULTIMATE'),
    ('CHOROMON_LINE_1', 6, 'Justimon', 'MEGA'),
    ('COTSUCOMON_LINE_1', 1, 'Cotsucomon', 'BABY'),
    ('COTSUCOMON_LINE_1', 2, 'Kakkinmon', 'BABY_II'),
    ('COTSUCOMON_LINE_1', 3, 'Ludomon', 'ROOKIE'),
    ('COTSUCOMON_LINE_1', 4, 'TiaLudomon', 'CHAMPION'),
    ('COTSUCOMON_LINE_1', 5, 'Durandamon', 'ULTIMATE'),
    ('COTSUCOMON_LINE_1', 6, 'Ragna Lordmon', 'MEGA'),
    ('CURIMON_LINE_1', 1, 'Curimon', 'BABY'),
    ('CURIMON_LINE_1', 2, 'Gurimon', 'BABY_II'),
    ('CURIMON_LINE_1', 3, 'Koemon', 'ROOKIE'),
    ('CURIMON_LINE_1', 4, 'Monmon', 'CHAMPION'),
    ('CURIMON_LINE_1', 5, 'Etemon', 'ULTIMATE'),
    ('CURIMON_LINE_1', 6, 'MetalEtemon', 'MEGA'),
    ('DOKIMON_LINE_1', 1, 'Dokimon', 'BABY'),
    ('DOKIMON_LINE_1', 2, 'Bibimon', 'BABY_II'),
    ('DOKIMON_LINE_1', 3, 'Kokuwamon', 'ROOKIE'),
    ('DOKIMON_LINE_1', 4, 'Guardromon', 'CHAMPION'),
    ('DOKIMON_LINE_1', 5, 'Andromon', 'ULTIMATE'),
    ('DOKIMON_LINE_1', 6, 'HiAndromon', 'MEGA'),
    ('FUFUMON_LINE_1', 1, 'Fufumon', 'BABY'),
    ('FUFUMON_LINE_1', 2, 'Kyokyomon', 'BABY_II'),
    ('FUFUMON_LINE_1', 3, 'Dracomon', 'ROOKIE'),
    ('FUFUMON_LINE_1', 4, 'Coredramon (Blue)', 'CHAMPION'),
    ('FUFUMON_LINE_1', 5, 'Wingdramon', 'ULTIMATE'),
    ('FUFUMON_LINE_1', 6, 'Slayerdramon', 'MEGA'),
    ('FUKAMON_LINE_1', 1, 'Fukamon', 'BABY'),
    ('FUKAMON_LINE_1', 2, 'Pukamon', 'BABY_II'),
    ('FUKAMON_LINE_1', 3, 'Betamon', 'ROOKIE'),
    ('FUKAMON_LINE_1', 4, 'Seadramon', 'CHAMPION'),
    ('FUKAMON_LINE_1', 5, 'MegaSeadramon', 'ULTIMATE'),
    ('FUKAMON_LINE_1', 6, 'MetalSeadramon', 'MEGA'),
    ('FUSAMON_LINE_1', 1, 'Fusamon', 'BABY'),
    ('FUSAMON_LINE_1', 2, 'Bowmon', 'BABY_II'),
    ('FUSAMON_LINE_1', 3, 'Salamon', 'ROOKIE'),
    ('FUSAMON_LINE_1', 4, 'BlackGatomon', 'CHAMPION'),
    ('FUSAMON_LINE_1', 5, 'LadyDevimon', 'ULTIMATE'),
    ('FUSAMON_LINE_1', 6, 'Lilithmon', 'MEGA'),
    ('KEEMON_LINE_1', 1, 'Keemon', 'BABY'),
    ('KEEMON_LINE_1', 2, 'Yarmon', 'BABY_II'),
    ('KEEMON_LINE_1', 3, 'Loogamon', 'ROOKIE'),
    ('KEEMON_LINE_1', 4, 'Fangmon', 'CHAMPION'),
    ('KEEMON_LINE_1', 5, 'Astamon', 'ULTIMATE'),
    ('KEEMON_LINE_1', 6, 'Belphemon: Sleep Mode', 'MEGA'),
    ('KEKOMON_LINE_1', 1, 'Kekomon', 'BABY'),
    ('KEKOMON_LINE_1', 2, 'Chapmon', 'BABY_II'),
    ('KEKOMON_LINE_1', 3, 'Kamemon', 'ROOKIE'),
    ('KEKOMON_LINE_1', 4, 'Gawappamon', 'CHAMPION'),
    ('KEKOMON_LINE_1', 5, 'GrapLeomon', 'ULTIMATE'),
    ('KEKOMON_LINE_1', 6, 'SaberLeomon', 'MEGA'),
    ('KETOMON_LINE_1', 1, 'Ketomon', 'BABY'),
    ('KETOMON_LINE_1', 2, 'Hopmon', 'BABY_II'),
    ('KETOMON_LINE_1', 3, 'Bearmon', 'ROOKIE'),
    ('KETOMON_LINE_1', 4, 'Gryzmon', 'CHAMPION'),
    ('KETOMON_LINE_1', 5, 'Grappu Leomon', 'ULTIMATE'),
    ('KETOMON_LINE_1', 6, 'BanchoLeomon', 'MEGA'),
    ('MOKUMON_LINE_1', 1, 'Mokumon', 'BABY'),
    ('MOKUMON_LINE_1', 2, 'Sunmon', 'BABY_II'),
    ('MOKUMON_LINE_1', 3, 'Coronamon', 'ROOKIE'),
    ('MOKUMON_LINE_1', 4, 'Firamon', 'CHAMPION'),
    ('MOKUMON_LINE_1', 5, 'Flaremon', 'ULTIMATE'),
    ('MOKUMON_LINE_1', 6, 'Apollomon', 'MEGA'),
    ('NYOKIMON_LINE_1', 1, 'Nyokimon', 'BABY'),
    ('NYOKIMON_LINE_1', 2, 'Budmon', 'BABY_II'),
    ('NYOKIMON_LINE_1', 3, 'Lalamon', 'ROOKIE'),
    ('NYOKIMON_LINE_1', 4, 'Sunflowmon', 'CHAMPION'),
    ('NYOKIMON_LINE_1', 5, 'Lilamon', 'ULTIMATE'),
    ('NYOKIMON_LINE_1', 6, 'Rosemon', 'MEGA'),
    ('PAFUMON_LINE_1', 1, 'Pafumon', 'BABY'),
    ('PAFUMON_LINE_1', 2, 'Kyaromon', 'BABY_II'),
    ('PAFUMON_LINE_1', 3, 'Gaomon', 'ROOKIE'),
    ('PAFUMON_LINE_1', 4, 'Gaogamon', 'CHAMPION'),
    ('PAFUMON_LINE_1', 5, 'MachGaogamon', 'ULTIMATE'),
    ('PAFUMON_LINE_1', 6, 'MirageGaogamon', 'MEGA'),
    ('PAOMON_LINE_1', 1, 'Paomon', 'BABY'),
    ('PAOMON_LINE_1', 2, 'Xiaomon', 'BABY_II'),
    ('PAOMON_LINE_1', 3, 'Labramon', 'ROOKIE'),
    ('PAOMON_LINE_1', 4, 'Dobermon', 'CHAMPION'),
    ('PAOMON_LINE_1', 5, 'Cerberumon', 'ULTIMATE'),
    ('PAOMON_LINE_1', 6, 'Plutomon', 'MEGA'),
    ('PETI_MERAMON_LINE_1', 1, 'Peti Meramon', 'BABY'),
    ('PETI_MERAMON_LINE_1', 2, 'Candmon', 'BABY_II'),
    ('PETI_MERAMON_LINE_1', 3, 'Candlemon', 'ROOKIE'),
    ('PETI_MERAMON_LINE_1', 4, 'Meramon', 'CHAMPION'),
    ('PETI_MERAMON_LINE_1', 5, 'SkullMeramon', 'ULTIMATE'),
    ('PETI_MERAMON_LINE_1', 6, 'Boltmon', 'MEGA'),
    ('PETITMON_LINE_1', 1, 'Petitmon', 'BABY'),
    ('PETITMON_LINE_1', 2, 'Babydmon', 'BABY_II'),
    ('PETITMON_LINE_1', 3, 'Hackmon', 'ROOKIE'),
    ('PETITMON_LINE_1', 4, 'Bao Hackmon', 'CHAMPION'),
    ('PETITMON_LINE_1', 5, 'SaviorHackmon', 'ULTIMATE'),
    ('PETITMON_LINE_1', 6, 'Jesmon', 'MEGA'),
    ('PIPIMON_LINE_1', 1, 'Pipimon', 'BABY'),
    ('PIPIMON_LINE_1', 2, 'Frimon', 'BABY_II'),
    ('PIPIMON_LINE_1', 3, 'Lunamon', 'ROOKIE'),
    ('PIPIMON_LINE_1', 4, 'Lekismon', 'CHAMPION'),
    ('PIPIMON_LINE_1', 5, 'Crescemon', 'ULTIMATE'),
    ('PIPIMON_LINE_1', 6, 'Dianamon', 'MEGA'),
    ('PITCHMON_LINE_1', 1, 'Pitchmon', 'BABY'),
    ('PITCHMON_LINE_1', 2, 'Tunomon', 'BABY_II'),
    ('PITCHMON_LINE_1', 3, 'Ganimon', 'ROOKIE'),
    ('PITCHMON_LINE_1', 4, 'Hookmon', 'CHAMPION'),
    ('PITCHMON_LINE_1', 5, 'MarineDevimon', 'ULTIMATE'),
    ('PITCHMON_LINE_1', 6, 'Pukumon', 'MEGA'),
    ('POPOMON_LINE_1', 1, 'Popomon', 'BABY'),
    ('POPOMON_LINE_1', 2, 'Wanyamon', 'BABY_II'),
    ('POPOMON_LINE_1', 3, 'Liollmon', 'ROOKIE'),
    ('POPOMON_LINE_1', 4, 'Liamon', 'CHAMPION'),
    ('POPOMON_LINE_1', 5, 'LoaderLiomon', 'ULTIMATE'),
    ('POPOMON_LINE_1', 6, 'HeavyLeomon', 'MEGA'),
    ('PUPUMON_LINE_1', 1, 'Pupumon', 'BABY'),
    ('PUPUMON_LINE_1', 2, 'Puroromon', 'BABY_II'),
    ('PUPUMON_LINE_1', 3, 'Funbeemon', 'ROOKIE'),
    ('PUPUMON_LINE_1', 4, 'Waspmon', 'CHAMPION'),
    ('PUPUMON_LINE_1', 5, 'CannonBeemon', 'ULTIMATE'),
    ('PUPUMON_LINE_1', 6, 'TigerVespamon', 'MEGA'),
    ('PURURUMON_LINE_1', 1, 'Pururumon', 'BABY'),
    ('PURURUMON_LINE_1', 2, 'Poromon', 'BABY_II'),
    ('PURURUMON_LINE_1', 3, 'Hawkmon', 'ROOKIE'),
    ('PURURUMON_LINE_1', 4, 'Aquilamon', 'CHAMPION'),
    ('PURURUMON_LINE_1', 5, 'Silphymon', 'ULTIMATE'),
    ('PURURUMON_LINE_1', 6, 'Valkyrimon', 'MEGA'),
    ('PUTTIMON_LINE_1', 1, 'Puttimon', 'BABY'),
    ('PUTTIMON_LINE_1', 2, 'Cupimon', 'BABY_II'),
    ('PUTTIMON_LINE_1', 3, 'Plotmon', 'ROOKIE'),
    ('PUTTIMON_LINE_1', 4, 'Tailmon', 'CHAMPION'),
    ('PUTTIMON_LINE_1', 5, 'Angewomon', 'ULTIMATE'),
    ('PUTTIMON_LINE_1', 6, 'Ophanimon', 'MEGA'),
    ('PUWAMON_LINE_1', 1, 'Puwamon', 'BABY'),
    ('PUWAMON_LINE_1', 2, 'Pinamon', 'BABY_II'),
    ('PUWAMON_LINE_1', 3, 'Pomumon', 'ROOKIE'),
    ('PUWAMON_LINE_1', 4, 'Parasaurmon', 'CHAMPION'),
    ('PUWAMON_LINE_1', 5, 'Parrotmon', 'ULTIMATE'),
    ('PUWAMON_LINE_1', 6, 'Gryphonmon', 'MEGA'),
    ('PUYOMON_LINE_1', 1, 'Puyomon', 'BABY'),
    ('PUYOMON_LINE_1', 2, 'Puyoyomon', 'BABY_II'),
    ('PUYOMON_LINE_1', 3, 'Jellymon', 'ROOKIE'),
    ('PUYOMON_LINE_1', 4, 'TeslaJellymon', 'CHAMPION'),
    ('PUYOMON_LINE_1', 5, 'Amphimon', 'ULTIMATE'),
    ('PUYOMON_LINE_1', 6, 'Cthyllamon', 'MEGA'),
    ('PYONMON_LINE_1', 1, 'Pyonmon', 'BABY'),
    ('PYONMON_LINE_1', 2, 'Bosamon', 'BABY_II'),
    ('PYONMON_LINE_1', 3, 'Angoramon', 'ROOKIE'),
    ('PYONMON_LINE_1', 4, 'SymbareAngoramon', 'CHAMPION'),
    ('PYONMON_LINE_1', 5, 'Lamortmon', 'ULTIMATE'),
    ('PYONMON_LINE_1', 6, 'Diarbbitmon', 'MEGA'),
    ('RELEMON_LINE_1', 1, 'Relemon', 'BABY'),
    ('RELEMON_LINE_1', 2, 'Pokomon', 'BABY_II'),
    ('RELEMON_LINE_1', 3, 'Renamon', 'ROOKIE'),
    ('RELEMON_LINE_1', 4, 'Kyubimon', 'CHAMPION'),
    ('RELEMON_LINE_1', 5, 'Taomon', 'ULTIMATE'),
    ('RELEMON_LINE_1', 6, 'Sakuyamon', 'MEGA'),
    ('SUNAMON_LINE_1', 1, 'Sunamon', 'BABY'),
    ('SUNAMON_LINE_1', 2, 'Goromon', 'BABY_II'),
    ('SUNAMON_LINE_1', 3, 'Sunarizamon', 'ROOKIE'),
    ('SUNAMON_LINE_1', 4, 'Vermilimon', 'CHAMPION'),
    ('SUNAMON_LINE_1', 5, 'SkullGreymon', 'ULTIMATE'),
    ('SUNAMON_LINE_1', 6, 'Ebonwumon', 'MEGA'),
    ('TOMORIMON_LINE_1', 1, 'Tomorimon', 'BABY'),
    ('TOMORIMON_LINE_1', 2, 'Mochimon', 'BABY_II'),
    ('TOMORIMON_LINE_1', 3, 'Morphomon', 'ROOKIE'),
    ('TOMORIMON_LINE_1', 4, 'Dokugumon', 'CHAMPION'),
    ('TOMORIMON_LINE_1', 5, 'Okuwamon', 'ULTIMATE'),
    ('TOMORIMON_LINE_1', 6, 'QueenBeemon', 'MEGA'),
    ('TORIKARA_BALLMON_LINE_1', 1, 'Torikara Ballmon', 'BABY'),
    ('TORIKARA_BALLMON_LINE_1', 2, 'Kapurimon', 'BABY_II'),
    ('TORIKARA_BALLMON_LINE_1', 3, 'Kotemon', 'ROOKIE'),
    ('TORIKARA_BALLMON_LINE_1', 4, 'Gladimon', 'CHAMPION'),
    ('TORIKARA_BALLMON_LINE_1', 5, 'Knightmon', 'ULTIMATE'),
    ('TORIKARA_BALLMON_LINE_1', 6, 'Craniummon', 'MEGA'),
    ('TSUBUMON_LINE_1', 1, 'Tsubumon', 'BABY'),
    ('TSUBUMON_LINE_1', 2, 'Upamon', 'BABY_II'),
    ('TSUBUMON_LINE_1', 3, 'Armadimon', 'ROOKIE'),
    ('TSUBUMON_LINE_1', 4, 'Ankylomon', 'CHAMPION'),
    ('TSUBUMON_LINE_1', 5, 'Triceramon', 'ULTIMATE'),
    ('TSUBUMON_LINE_1', 6, 'RustTyrannomon', 'MEGA'),
    ('YOLKMON_LINE_1', 1, 'Yolkmon', 'BABY'),
    ('YOLKMON_LINE_1', 2, 'Fluffymon', 'BABY_II'),
    ('YOLKMON_LINE_1', 3, 'Pteromon', 'ROOKIE'),
    ('YOLKMON_LINE_1', 4, 'Galemon', 'CHAMPION'),
    ('YOLKMON_LINE_1', 5, 'GrandGalemon', 'ULTIMATE'),
    ('YOLKMON_LINE_1', 6, 'Zephagamon', 'MEGA'),
    ('ZURUMON_LINE_1', 1, 'Zurumon', 'BABY'),
    ('ZURUMON_LINE_1', 2, 'Pagumon', 'BABY_II'),
    ('ZURUMON_LINE_1', 3, 'Ghostmon', 'ROOKIE'),
    ('ZURUMON_LINE_1', 4, 'Bakemon', 'CHAMPION'),
    ('ZURUMON_LINE_1', 5, 'Phantomon', 'ULTIMATE'),
    ('ZURUMON_LINE_1', 6, 'Piemon', 'MEGA')
) AS data(line_code, step_order, digimon_name, stage)
JOIN evolution_lines line ON line.code = data.line_code
JOIN digimon_infos info ON info.name = data.digimon_name AND info.stage = data.stage
ON CONFLICT (evolution_line_id, step_order) DO UPDATE SET
    digimon_info_id = EXCLUDED.digimon_info_id,
    stage = EXCLUDED.stage,
    required_level = EXCLUDED.required_level;

DO $$
DECLARE
    inserted_steps INTEGER;
BEGIN
    SELECT COUNT(*) INTO inserted_steps
      FROM evolution_line_steps step
      JOIN evolution_lines line ON line.id = step.evolution_line_id
      JOIN available_contents content ON content.id = line.content_id
     WHERE content.code = 'EVOLUTION_EXPANSION_2';
    IF inserted_steps <> 222 THEN
        RAISE EXCEPTION 'Expected 222 evolution steps for EVOLUTION_EXPANSION_2, found %', inserted_steps;
    END IF;
END $$;
