INSERT INTO evolution_step_materials (evolution_line_step_id, material_code, quantity, description)
SELECT step.id, data.material_code, data.quantity, data.description
FROM (
    VALUES
    ('ALGOMON_LINE_1', 2, 'FRAGMENT_ALGOMONBABYII', 5, 'Fragmento do Algomon (Baby II)'),
    ('ALGOMON_LINE_1', 3, 'FRAGMENT_ALGOMONCHILD', 10, 'Fragmento do Algomon (Child)'),
    ('ALGOMON_LINE_1', 4, 'FRAGMENT_ALGOMONADULT', 20, 'Fragmento do Algomon (Adult)'),
    ('ALGOMON_LINE_1', 5, 'FRAGMENT_ALGOMONPERFECT', 30, 'Fragmento do Algomon (Perfect)'),
    ('ALGOMON_LINE_1', 6, 'FRAGMENT_ALGOMONULTIMATE', 50, 'Fragmento do Algomon (Ultimate)'),
    ('BOMBMON_LINE_1', 2, 'FRAGMENT_MISSIMON', 5, 'Fragmento do Missimon'),
    ('BOMBMON_LINE_1', 3, 'FRAGMENT_COMMANDRAMON', 10, 'Fragmento do Commandramon'),
    ('BOMBMON_LINE_1', 4, 'FRAGMENT_SEALSDRAMON', 20, 'Fragmento do Sealsdramon'),
    ('BOMBMON_LINE_1', 5, 'FRAGMENT_TANKDRAMON', 30, 'Fragmento do Tankdramon'),
    ('BOMBMON_LINE_1', 6, 'FRAGMENT_DARKDRAMON', 50, 'Fragmento do Darkdramon'),
    ('BOMMON_LINE_1', 2, 'FRAGMENT_KAPURIMON', 5, 'Fragmento do Kapurimon'),
    ('BOMMON_LINE_1', 3, 'FRAGMENT_IMPMON', 10, 'Fragmento do Impmon'),
    ('BOMMON_LINE_1', 4, 'FRAGMENT_BAKEMON', 20, 'Fragmento do Bakemon'),
    ('BOMMON_LINE_1', 5, 'FRAGMENT_MYOTISMON', 30, 'Fragmento do Myotismon'),
    ('BOMMON_LINE_1', 6, 'FRAGMENT_BEELZEBUMON', 50, 'Fragmento do Beelzebumon'),
    ('BUBBMON_LINE_1', 2, 'FRAGMENT_MOCHIMON', 5, 'Fragmento do Mochimon'),
    ('BUBBMON_LINE_1', 3, 'FRAGMENT_OTAMAMON', 10, 'Fragmento do Otamamon'),
    ('BUBBMON_LINE_1', 4, 'FRAGMENT_GEKOMON', 20, 'Fragmento do Gekomon'),
    ('BUBBMON_LINE_1', 5, 'FRAGMENT_SHOGUNGEKOMON', 30, 'Fragmento do ShogunGekomon'),
    ('BUBBMON_LINE_1', 6, 'FRAGMENT_MARINEANGEMON', 50, 'Fragmento do MarineAngemon'),
    ('CHIBICKMON_LINE_1', 2, 'FRAGMENT_PICKMON', 5, 'Fragmento do Pickmon'),
    ('CHIBICKMON_LINE_1', 3, 'FRAGMENT_STARMONS', 10, 'Fragmento do Starmons'),
    ('CHIBICKMON_LINE_1', 4, 'FRAGMENT_SHOUTMON', 20, 'Fragmento do Shoutmon'),
    ('CHIBICKMON_LINE_1', 5, 'FRAGMENT_OMEGASHOUTMON', 30, 'Fragmento do OmegaShoutmon'),
    ('CHIBICKMON_LINE_1', 6, 'FRAGMENT_SHOUTMONX7SUPERIORMODE', 50, 'Fragmento do Shoutmon X7 (Superior Mode)'),
    ('CHOROMON_LINE_1', 2, 'FRAGMENT_PAGUMON', 5, 'Fragmento do Pagumon'),
    ('CHOROMON_LINE_1', 3, 'FRAGMENT_GAZIMON', 10, 'Fragmento do Gazimon'),
    ('CHOROMON_LINE_1', 4, 'FRAGMENT_DEVIDRAMON', 20, 'Fragmento do Devidramon'),
    ('CHOROMON_LINE_1', 5, 'FRAGMENT_CYBERDRAMON', 30, 'Fragmento do Cyberdramon'),
    ('CHOROMON_LINE_1', 6, 'FRAGMENT_JUSTIMON', 50, 'Fragmento do Justimon'),
    ('COTSUCOMON_LINE_1', 2, 'FRAGMENT_KAKKINMON', 5, 'Fragmento do Kakkinmon'),
    ('COTSUCOMON_LINE_1', 3, 'FRAGMENT_LUDOMON', 10, 'Fragmento do Ludomon'),
    ('COTSUCOMON_LINE_1', 4, 'FRAGMENT_TIALUDOMON', 20, 'Fragmento do TiaLudomon'),
    ('COTSUCOMON_LINE_1', 5, 'FRAGMENT_DURANDAMON', 30, 'Fragmento do Durandamon'),
    ('COTSUCOMON_LINE_1', 6, 'FRAGMENT_RAGNALORDMON', 50, 'Fragmento do Ragna Lordmon'),
    ('CURIMON_LINE_1', 2, 'FRAGMENT_GURIMON', 5, 'Fragmento do Gurimon'),
    ('CURIMON_LINE_1', 3, 'FRAGMENT_KOEMON', 10, 'Fragmento do Koemon'),
    ('CURIMON_LINE_1', 4, 'FRAGMENT_MONMON', 20, 'Fragmento do Monmon'),
    ('CURIMON_LINE_1', 5, 'FRAGMENT_ETEMON', 30, 'Fragmento do Etemon'),
    ('CURIMON_LINE_1', 6, 'FRAGMENT_METALETEMON', 50, 'Fragmento do MetalEtemon'),
    ('DOKIMON_LINE_1', 2, 'FRAGMENT_BIBIMON', 5, 'Fragmento do Bibimon'),
    ('DOKIMON_LINE_1', 3, 'FRAGMENT_KOKUWAMON', 10, 'Fragmento do Kokuwamon'),
    ('DOKIMON_LINE_1', 4, 'FRAGMENT_GUARDROMON', 20, 'Fragmento do Guardromon'),
    ('DOKIMON_LINE_1', 5, 'FRAGMENT_ANDROMON', 30, 'Fragmento do Andromon'),
    ('DOKIMON_LINE_1', 6, 'FRAGMENT_HIANDROMON', 50, 'Fragmento do HiAndromon'),
    ('FUFUMON_LINE_1', 2, 'FRAGMENT_KYOKYOMON', 5, 'Fragmento do Kyokyomon'),
    ('FUFUMON_LINE_1', 3, 'FRAGMENT_DRACOMON', 10, 'Fragmento do Dracomon'),
    ('FUFUMON_LINE_1', 4, 'FRAGMENT_COREDRAMONBLUE', 20, 'Fragmento do Coredramon (Blue)'),
    ('FUFUMON_LINE_1', 5, 'FRAGMENT_WINGDRAMON', 30, 'Fragmento do Wingdramon'),
    ('FUFUMON_LINE_1', 6, 'FRAGMENT_SLAYERDRAMON', 50, 'Fragmento do Slayerdramon'),
    ('FUKAMON_LINE_1', 2, 'FRAGMENT_PUKAMON', 5, 'Fragmento do Pukamon'),
    ('FUKAMON_LINE_1', 3, 'FRAGMENT_BETAMON', 10, 'Fragmento do Betamon'),
    ('FUKAMON_LINE_1', 4, 'FRAGMENT_SEADRAMON', 20, 'Fragmento do Seadramon'),
    ('FUKAMON_LINE_1', 5, 'FRAGMENT_MEGASEADRAMON', 30, 'Fragmento do MegaSeadramon'),
    ('FUKAMON_LINE_1', 6, 'FRAGMENT_METALSEADRAMON', 50, 'Fragmento do MetalSeadramon'),
    ('FUSAMON_LINE_1', 2, 'FRAGMENT_BOWMON', 5, 'Fragmento do Bowmon'),
    ('FUSAMON_LINE_1', 3, 'FRAGMENT_SALAMON', 10, 'Fragmento do Salamon'),
    ('FUSAMON_LINE_1', 4, 'FRAGMENT_BLACKGATOMON', 20, 'Fragmento do BlackGatomon'),
    ('FUSAMON_LINE_1', 5, 'FRAGMENT_LADYDEVIMON', 30, 'Fragmento do LadyDevimon'),
    ('FUSAMON_LINE_1', 6, 'FRAGMENT_LILITHMON', 50, 'Fragmento do Lilithmon'),
    ('KEEMON_LINE_1', 2, 'FRAGMENT_YARMON', 5, 'Fragmento do Yarmon'),
    ('KEEMON_LINE_1', 3, 'FRAGMENT_LOOGAMON', 10, 'Fragmento do Loogamon'),
    ('KEEMON_LINE_1', 4, 'FRAGMENT_FANGMON', 20, 'Fragmento do Fangmon'),
    ('KEEMON_LINE_1', 5, 'FRAGMENT_ASTAMON', 30, 'Fragmento do Astamon'),
    ('KEEMON_LINE_1', 6, 'FRAGMENT_BELPHEMONSLEEPMODE', 50, 'Fragmento do Belphemon: Sleep Mode'),
    ('KEKOMON_LINE_1', 2, 'FRAGMENT_CHAPMON', 5, 'Fragmento do Chapmon'),
    ('KEKOMON_LINE_1', 3, 'FRAGMENT_KAMEMON', 10, 'Fragmento do Kamemon'),
    ('KEKOMON_LINE_1', 4, 'FRAGMENT_GAWAPPAMON', 20, 'Fragmento do Gawappamon'),
    ('KEKOMON_LINE_1', 5, 'FRAGMENT_GRAPLEOMON', 30, 'Fragmento do GrapLeomon'),
    ('KEKOMON_LINE_1', 6, 'FRAGMENT_SABERLEOMON', 50, 'Fragmento do SaberLeomon'),
    ('KETOMON_LINE_1', 2, 'FRAGMENT_HOPMON', 5, 'Fragmento do Hopmon'),
    ('KETOMON_LINE_1', 3, 'FRAGMENT_BEARMON', 10, 'Fragmento do Bearmon'),
    ('KETOMON_LINE_1', 4, 'FRAGMENT_GRYZMON', 20, 'Fragmento do Gryzmon'),
    ('KETOMON_LINE_1', 5, 'FRAGMENT_GRAPPULEOMON', 30, 'Fragmento do Grappu Leomon'),
    ('KETOMON_LINE_1', 6, 'FRAGMENT_BANCHOLEOMON', 50, 'Fragmento do BanchoLeomon'),
    ('MOKUMON_LINE_1', 2, 'FRAGMENT_SUNMON', 5, 'Fragmento do Sunmon'),
    ('MOKUMON_LINE_1', 3, 'FRAGMENT_CORONAMON', 10, 'Fragmento do Coronamon'),
    ('MOKUMON_LINE_1', 4, 'FRAGMENT_FIRAMON', 20, 'Fragmento do Firamon'),
    ('MOKUMON_LINE_1', 5, 'FRAGMENT_FLAREMON', 30, 'Fragmento do Flaremon'),
    ('MOKUMON_LINE_1', 6, 'FRAGMENT_APOLLOMON', 50, 'Fragmento do Apollomon'),
    ('NYOKIMON_LINE_1', 2, 'FRAGMENT_BUDMON', 5, 'Fragmento do Budmon'),
    ('NYOKIMON_LINE_1', 3, 'FRAGMENT_LALAMON', 10, 'Fragmento do Lalamon'),
    ('NYOKIMON_LINE_1', 4, 'FRAGMENT_SUNFLOWMON', 20, 'Fragmento do Sunflowmon'),
    ('NYOKIMON_LINE_1', 5, 'FRAGMENT_LILAMON', 30, 'Fragmento do Lilamon'),
    ('NYOKIMON_LINE_1', 6, 'FRAGMENT_ROSEMON', 50, 'Fragmento do Rosemon'),
    ('PAFUMON_LINE_1', 2, 'FRAGMENT_KYAROMON', 5, 'Fragmento do Kyaromon'),
    ('PAFUMON_LINE_1', 3, 'FRAGMENT_GAOMON', 10, 'Fragmento do Gaomon'),
    ('PAFUMON_LINE_1', 4, 'FRAGMENT_GAOGAMON', 20, 'Fragmento do Gaogamon'),
    ('PAFUMON_LINE_1', 5, 'FRAGMENT_MACHGAOGAMON', 30, 'Fragmento do MachGaogamon'),
    ('PAFUMON_LINE_1', 6, 'FRAGMENT_MIRAGEGAOGAMON', 50, 'Fragmento do MirageGaogamon'),
    ('PAOMON_LINE_1', 2, 'FRAGMENT_XIAOMON', 5, 'Fragmento do Xiaomon'),
    ('PAOMON_LINE_1', 3, 'FRAGMENT_LABRAMON', 10, 'Fragmento do Labramon'),
    ('PAOMON_LINE_1', 4, 'FRAGMENT_DOBERMON', 20, 'Fragmento do Dobermon'),
    ('PAOMON_LINE_1', 5, 'FRAGMENT_CERBERUMON', 30, 'Fragmento do Cerberumon'),
    ('PAOMON_LINE_1', 6, 'FRAGMENT_PLUTOMON', 50, 'Fragmento do Plutomon'),
    ('PETI_MERAMON_LINE_1', 2, 'FRAGMENT_CANDMON', 5, 'Fragmento do Candmon'),
    ('PETI_MERAMON_LINE_1', 3, 'FRAGMENT_CANDLEMON', 10, 'Fragmento do Candlemon'),
    ('PETI_MERAMON_LINE_1', 4, 'FRAGMENT_MERAMON', 20, 'Fragmento do Meramon'),
    ('PETI_MERAMON_LINE_1', 5, 'FRAGMENT_SKULLMERAMON', 30, 'Fragmento do SkullMeramon'),
    ('PETI_MERAMON_LINE_1', 6, 'FRAGMENT_BOLTMON', 50, 'Fragmento do Boltmon'),
    ('PETITMON_LINE_1', 2, 'FRAGMENT_BABYDMON', 5, 'Fragmento do Babydmon'),
    ('PETITMON_LINE_1', 3, 'FRAGMENT_HACKMON', 10, 'Fragmento do Hackmon'),
    ('PETITMON_LINE_1', 4, 'FRAGMENT_BAOHACKMON', 20, 'Fragmento do Bao Hackmon'),
    ('PETITMON_LINE_1', 5, 'FRAGMENT_SAVIORHACKMON', 30, 'Fragmento do SaviorHackmon'),
    ('PETITMON_LINE_1', 6, 'FRAGMENT_JESMON', 50, 'Fragmento do Jesmon'),
    ('PIPIMON_LINE_1', 2, 'FRAGMENT_FRIMON', 5, 'Fragmento do Frimon'),
    ('PIPIMON_LINE_1', 3, 'FRAGMENT_LUNAMON', 10, 'Fragmento do Lunamon'),
    ('PIPIMON_LINE_1', 4, 'FRAGMENT_LEKISMON', 20, 'Fragmento do Lekismon'),
    ('PIPIMON_LINE_1', 5, 'FRAGMENT_CRESCEMON', 30, 'Fragmento do Crescemon'),
    ('PIPIMON_LINE_1', 6, 'FRAGMENT_DIANAMON', 50, 'Fragmento do Dianamon'),
    ('PITCHMON_LINE_1', 2, 'FRAGMENT_TUNOMON', 5, 'Fragmento do Tunomon'),
    ('PITCHMON_LINE_1', 3, 'FRAGMENT_GANIMON', 10, 'Fragmento do Ganimon'),
    ('PITCHMON_LINE_1', 4, 'FRAGMENT_HOOKMON', 20, 'Fragmento do Hookmon'),
    ('PITCHMON_LINE_1', 5, 'FRAGMENT_MARINEDEVIMON', 30, 'Fragmento do MarineDevimon'),
    ('PITCHMON_LINE_1', 6, 'FRAGMENT_PUKUMON', 50, 'Fragmento do Pukumon'),
    ('POPOMON_LINE_1', 2, 'FRAGMENT_WANYAMON', 5, 'Fragmento do Wanyamon'),
    ('POPOMON_LINE_1', 3, 'FRAGMENT_LIOLLMON', 10, 'Fragmento do Liollmon'),
    ('POPOMON_LINE_1', 4, 'FRAGMENT_LIAMON', 20, 'Fragmento do Liamon'),
    ('POPOMON_LINE_1', 5, 'FRAGMENT_LOADERLIOMON', 30, 'Fragmento do LoaderLiomon'),
    ('POPOMON_LINE_1', 6, 'FRAGMENT_HEAVYLEOMON', 50, 'Fragmento do HeavyLeomon'),
    ('PUPUMON_LINE_1', 2, 'FRAGMENT_PUROROMON', 5, 'Fragmento do Puroromon'),
    ('PUPUMON_LINE_1', 3, 'FRAGMENT_FUNBEEMON', 10, 'Fragmento do Funbeemon'),
    ('PUPUMON_LINE_1', 4, 'FRAGMENT_WASPMON', 20, 'Fragmento do Waspmon'),
    ('PUPUMON_LINE_1', 5, 'FRAGMENT_CANNONBEEMON', 30, 'Fragmento do CannonBeemon'),
    ('PUPUMON_LINE_1', 6, 'FRAGMENT_TIGERVESPAMON', 50, 'Fragmento do TigerVespamon'),
    ('PURURUMON_LINE_1', 2, 'FRAGMENT_POROMON', 5, 'Fragmento do Poromon'),
    ('PURURUMON_LINE_1', 3, 'FRAGMENT_HAWKMON', 10, 'Fragmento do Hawkmon'),
    ('PURURUMON_LINE_1', 4, 'FRAGMENT_AQUILAMON', 20, 'Fragmento do Aquilamon'),
    ('PURURUMON_LINE_1', 5, 'FRAGMENT_SILPHYMON', 30, 'Fragmento do Silphymon'),
    ('PURURUMON_LINE_1', 6, 'FRAGMENT_VALKYRIMON', 50, 'Fragmento do Valkyrimon'),
    ('PUTTIMON_LINE_1', 2, 'FRAGMENT_CUPIMON', 5, 'Fragmento do Cupimon'),
    ('PUTTIMON_LINE_1', 3, 'FRAGMENT_PLOTMON', 10, 'Fragmento do Plotmon'),
    ('PUTTIMON_LINE_1', 4, 'FRAGMENT_TAILMON', 20, 'Fragmento do Tailmon'),
    ('PUTTIMON_LINE_1', 5, 'FRAGMENT_ANGEWOMON', 30, 'Fragmento do Angewomon'),
    ('PUTTIMON_LINE_1', 6, 'FRAGMENT_OPHANIMON', 50, 'Fragmento do Ophanimon'),
    ('PUWAMON_LINE_1', 2, 'FRAGMENT_PINAMON', 5, 'Fragmento do Pinamon'),
    ('PUWAMON_LINE_1', 3, 'FRAGMENT_POMUMON', 10, 'Fragmento do Pomumon'),
    ('PUWAMON_LINE_1', 4, 'FRAGMENT_PARASAURMON', 20, 'Fragmento do Parasaurmon'),
    ('PUWAMON_LINE_1', 5, 'FRAGMENT_PARROTMON', 30, 'Fragmento do Parrotmon'),
    ('PUWAMON_LINE_1', 6, 'FRAGMENT_GRYPHONMON', 50, 'Fragmento do Gryphonmon'),
    ('PUYOMON_LINE_1', 2, 'FRAGMENT_PUYOYOMON', 5, 'Fragmento do Puyoyomon'),
    ('PUYOMON_LINE_1', 3, 'FRAGMENT_JELLYMON', 10, 'Fragmento do Jellymon'),
    ('PUYOMON_LINE_1', 4, 'FRAGMENT_TESLAJELLYMON', 20, 'Fragmento do TeslaJellymon'),
    ('PUYOMON_LINE_1', 5, 'FRAGMENT_AMPHIMON', 30, 'Fragmento do Amphimon'),
    ('PUYOMON_LINE_1', 6, 'FRAGMENT_CTHYLLAMON', 50, 'Fragmento do Cthyllamon'),
    ('PYONMON_LINE_1', 2, 'FRAGMENT_BOSAMON', 5, 'Fragmento do Bosamon'),
    ('PYONMON_LINE_1', 3, 'FRAGMENT_ANGORAMON', 10, 'Fragmento do Angoramon'),
    ('PYONMON_LINE_1', 4, 'FRAGMENT_SYMBAREANGORAMON', 20, 'Fragmento do SymbareAngoramon'),
    ('PYONMON_LINE_1', 5, 'FRAGMENT_LAMORTMON', 30, 'Fragmento do Lamortmon'),
    ('PYONMON_LINE_1', 6, 'FRAGMENT_DIARBBITMON', 50, 'Fragmento do Diarbbitmon'),
    ('RELEMON_LINE_1', 2, 'FRAGMENT_POKOMON', 5, 'Fragmento do Pokomon'),
    ('RELEMON_LINE_1', 3, 'FRAGMENT_RENAMON', 10, 'Fragmento do Renamon'),
    ('RELEMON_LINE_1', 4, 'FRAGMENT_KYUBIMON', 20, 'Fragmento do Kyubimon'),
    ('RELEMON_LINE_1', 5, 'FRAGMENT_TAOMON', 30, 'Fragmento do Taomon'),
    ('RELEMON_LINE_1', 6, 'FRAGMENT_SAKUYAMON', 50, 'Fragmento do Sakuyamon'),
    ('SUNAMON_LINE_1', 2, 'FRAGMENT_GOROMON', 5, 'Fragmento do Goromon'),
    ('SUNAMON_LINE_1', 3, 'FRAGMENT_SUNARIZAMON', 10, 'Fragmento do Sunarizamon'),
    ('SUNAMON_LINE_1', 4, 'FRAGMENT_VERMILIMON', 20, 'Fragmento do Vermilimon'),
    ('SUNAMON_LINE_1', 5, 'FRAGMENT_SKULLGREYMON', 30, 'Fragmento do SkullGreymon'),
    ('SUNAMON_LINE_1', 6, 'FRAGMENT_EBONWUMON', 50, 'Fragmento do Ebonwumon'),
    ('TOMORIMON_LINE_1', 2, 'FRAGMENT_MOCHIMON', 5, 'Fragmento do Mochimon'),
    ('TOMORIMON_LINE_1', 3, 'FRAGMENT_MORPHOMON', 10, 'Fragmento do Morphomon'),
    ('TOMORIMON_LINE_1', 4, 'FRAGMENT_DOKUGUMON', 20, 'Fragmento do Dokugumon'),
    ('TOMORIMON_LINE_1', 5, 'FRAGMENT_OKUWAMON', 30, 'Fragmento do Okuwamon'),
    ('TOMORIMON_LINE_1', 6, 'FRAGMENT_QUEENBEEMON', 50, 'Fragmento do QueenBeemon'),
    ('TORIKARA_BALLMON_LINE_1', 2, 'FRAGMENT_KAPURIMON', 5, 'Fragmento do Kapurimon'),
    ('TORIKARA_BALLMON_LINE_1', 3, 'FRAGMENT_KOTEMON', 10, 'Fragmento do Kotemon'),
    ('TORIKARA_BALLMON_LINE_1', 4, 'FRAGMENT_GLADIMON', 20, 'Fragmento do Gladimon'),
    ('TORIKARA_BALLMON_LINE_1', 5, 'FRAGMENT_KNIGHTMON', 30, 'Fragmento do Knightmon'),
    ('TORIKARA_BALLMON_LINE_1', 6, 'FRAGMENT_CRANIUMMON', 50, 'Fragmento do Craniummon'),
    ('TSUBUMON_LINE_1', 2, 'FRAGMENT_UPAMON', 5, 'Fragmento do Upamon'),
    ('TSUBUMON_LINE_1', 3, 'FRAGMENT_ARMADIMON', 10, 'Fragmento do Armadimon'),
    ('TSUBUMON_LINE_1', 4, 'FRAGMENT_ANKYLOMON', 20, 'Fragmento do Ankylomon'),
    ('TSUBUMON_LINE_1', 5, 'FRAGMENT_TRICERAMON', 30, 'Fragmento do Triceramon'),
    ('TSUBUMON_LINE_1', 6, 'FRAGMENT_RUSTTYRANNOMON', 50, 'Fragmento do RustTyrannomon'),
    ('YOLKMON_LINE_1', 2, 'FRAGMENT_FLUFFYMON', 5, 'Fragmento do Fluffymon'),
    ('YOLKMON_LINE_1', 3, 'FRAGMENT_PTEROMON', 10, 'Fragmento do Pteromon'),
    ('YOLKMON_LINE_1', 4, 'FRAGMENT_GALEMON', 20, 'Fragmento do Galemon'),
    ('YOLKMON_LINE_1', 5, 'FRAGMENT_GRANDGALEMON', 30, 'Fragmento do GrandGalemon'),
    ('YOLKMON_LINE_1', 6, 'FRAGMENT_ZEPHAGAMON', 50, 'Fragmento do Zephagamon'),
    ('ZURUMON_LINE_1', 2, 'FRAGMENT_PAGUMON', 5, 'Fragmento do Pagumon'),
    ('ZURUMON_LINE_1', 3, 'FRAGMENT_GHOSTMON', 10, 'Fragmento do Ghostmon'),
    ('ZURUMON_LINE_1', 4, 'FRAGMENT_BAKEMON', 20, 'Fragmento do Bakemon'),
    ('ZURUMON_LINE_1', 5, 'FRAGMENT_PHANTOMON', 30, 'Fragmento do Phantomon'),
    ('ZURUMON_LINE_1', 6, 'FRAGMENT_PIEMON', 50, 'Fragmento do Piemon')
) AS data(line_code, step_order, material_code, quantity, description)
JOIN evolution_lines line ON line.code = data.line_code
JOIN evolution_line_steps step ON step.evolution_line_id = line.id AND step.step_order = data.step_order
ON CONFLICT DO NOTHING;

DO $$
DECLARE
    material_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO material_count
      FROM evolution_step_materials material
      JOIN evolution_line_steps step ON step.id = material.evolution_line_step_id
      JOIN evolution_lines line ON line.id = step.evolution_line_id
      JOIN available_contents content ON content.id = line.content_id
     WHERE content.code = 'EVOLUTION_EXPANSION_2'
       AND step.step_order BETWEEN 2 AND 6;
    IF material_count <> 185 THEN
        RAISE EXCEPTION 'Expected 185 materials for EVOLUTION_EXPANSION_2, found %', material_count;
    END IF;
END $$;
