INSERT INTO item_definitions (
    code, name, description, category, stackable, buy_price, sell_price,
    tradable, sellable, usable, max_stack, rarity, icon
)
VALUES
    ('FRAGMENT_ALGOMONBABYII', 'Fragmento do Algomon (Baby II)', 'Fragmento para evoluir para Algomon (Baby II).', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_ALGOMONCHILD', 'Fragmento do Algomon (Child)', 'Fragmento para evoluir para Algomon (Child).', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_ALGOMONADULT', 'Fragmento do Algomon (Adult)', 'Fragmento para evoluir para Algomon (Adult).', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_ALGOMONPERFECT', 'Fragmento do Algomon (Perfect)', 'Fragmento para evoluir para Algomon (Perfect).', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_ALGOMONULTIMATE', 'Fragmento do Algomon (Ultimate)', 'Fragmento para evoluir para Algomon (Ultimate).', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_MISSIMON', 'Fragmento do Missimon', 'Fragmento para evoluir para Missimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_COMMANDRAMON', 'Fragmento do Commandramon', 'Fragmento para evoluir para Commandramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_SEALSDRAMON', 'Fragmento do Sealsdramon', 'Fragmento para evoluir para Sealsdramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_TANKDRAMON', 'Fragmento do Tankdramon', 'Fragmento para evoluir para Tankdramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_DARKDRAMON', 'Fragmento do Darkdramon', 'Fragmento para evoluir para Darkdramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_KAPURIMON', 'Fragmento do Kapurimon', 'Fragmento para evoluir para Kapurimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_IMPMON', 'Fragmento do Impmon', 'Fragmento para evoluir para Impmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_BAKEMON', 'Fragmento do Bakemon', 'Fragmento para evoluir para Bakemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_MYOTISMON', 'Fragmento do Myotismon', 'Fragmento para evoluir para Myotismon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_BEELZEBUMON', 'Fragmento do Beelzebumon', 'Fragmento para evoluir para Beelzebumon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_MOCHIMON', 'Fragmento do Mochimon', 'Fragmento para evoluir para Mochimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_OTAMAMON', 'Fragmento do Otamamon', 'Fragmento para evoluir para Otamamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_GEKOMON', 'Fragmento do Gekomon', 'Fragmento para evoluir para Gekomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_SHOGUNGEKOMON', 'Fragmento do ShogunGekomon', 'Fragmento para evoluir para ShogunGekomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_MARINEANGEMON', 'Fragmento do MarineAngemon', 'Fragmento para evoluir para MarineAngemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_PICKMON', 'Fragmento do Pickmon', 'Fragmento para evoluir para Pickmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_STARMONS', 'Fragmento do Starmons', 'Fragmento para evoluir para Starmons.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_SHOUTMON', 'Fragmento do Shoutmon', 'Fragmento para evoluir para Shoutmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_OMEGASHOUTMON', 'Fragmento do OmegaShoutmon', 'Fragmento para evoluir para OmegaShoutmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_SHOUTMONX7SUPERIORMODE', 'Fragmento do Shoutmon X7 (Superior Mode)', 'Fragmento para evoluir para Shoutmon X7 (Superior Mode).', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_PAGUMON', 'Fragmento do Pagumon', 'Fragmento para evoluir para Pagumon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_GAZIMON', 'Fragmento do Gazimon', 'Fragmento para evoluir para Gazimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_DEVIDRAMON', 'Fragmento do Devidramon', 'Fragmento para evoluir para Devidramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_CYBERDRAMON', 'Fragmento do Cyberdramon', 'Fragmento para evoluir para Cyberdramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_JUSTIMON', 'Fragmento do Justimon', 'Fragmento para evoluir para Justimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_KAKKINMON', 'Fragmento do Kakkinmon', 'Fragmento para evoluir para Kakkinmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_LUDOMON', 'Fragmento do Ludomon', 'Fragmento para evoluir para Ludomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_TIALUDOMON', 'Fragmento do TiaLudomon', 'Fragmento para evoluir para TiaLudomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_DURANDAMON', 'Fragmento do Durandamon', 'Fragmento para evoluir para Durandamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_RAGNALORDMON', 'Fragmento do Ragna Lordmon', 'Fragmento para evoluir para Ragna Lordmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_GURIMON', 'Fragmento do Gurimon', 'Fragmento para evoluir para Gurimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_KOEMON', 'Fragmento do Koemon', 'Fragmento para evoluir para Koemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_MONMON', 'Fragmento do Monmon', 'Fragmento para evoluir para Monmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_ETEMON', 'Fragmento do Etemon', 'Fragmento para evoluir para Etemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_METALETEMON', 'Fragmento do MetalEtemon', 'Fragmento para evoluir para MetalEtemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_BIBIMON', 'Fragmento do Bibimon', 'Fragmento para evoluir para Bibimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_KOKUWAMON', 'Fragmento do Kokuwamon', 'Fragmento para evoluir para Kokuwamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_GUARDROMON', 'Fragmento do Guardromon', 'Fragmento para evoluir para Guardromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_ANDROMON', 'Fragmento do Andromon', 'Fragmento para evoluir para Andromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_HIANDROMON', 'Fragmento do HiAndromon', 'Fragmento para evoluir para HiAndromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_KYOKYOMON', 'Fragmento do Kyokyomon', 'Fragmento para evoluir para Kyokyomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_DRACOMON', 'Fragmento do Dracomon', 'Fragmento para evoluir para Dracomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_COREDRAMONBLUE', 'Fragmento do Coredramon (Blue)', 'Fragmento para evoluir para Coredramon (Blue).', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_WINGDRAMON', 'Fragmento do Wingdramon', 'Fragmento para evoluir para Wingdramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_SLAYERDRAMON', 'Fragmento do Slayerdramon', 'Fragmento para evoluir para Slayerdramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_PUKAMON', 'Fragmento do Pukamon', 'Fragmento para evoluir para Pukamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_BETAMON', 'Fragmento do Betamon', 'Fragmento para evoluir para Betamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_SEADRAMON', 'Fragmento do Seadramon', 'Fragmento para evoluir para Seadramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_MEGASEADRAMON', 'Fragmento do MegaSeadramon', 'Fragmento para evoluir para MegaSeadramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_METALSEADRAMON', 'Fragmento do MetalSeadramon', 'Fragmento para evoluir para MetalSeadramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_BOWMON', 'Fragmento do Bowmon', 'Fragmento para evoluir para Bowmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_SALAMON', 'Fragmento do Salamon', 'Fragmento para evoluir para Salamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_BLACKGATOMON', 'Fragmento do BlackGatomon', 'Fragmento para evoluir para BlackGatomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_LADYDEVIMON', 'Fragmento do LadyDevimon', 'Fragmento para evoluir para LadyDevimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_LILITHMON', 'Fragmento do Lilithmon', 'Fragmento para evoluir para Lilithmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_YARMON', 'Fragmento do Yarmon', 'Fragmento para evoluir para Yarmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_LOOGAMON', 'Fragmento do Loogamon', 'Fragmento para evoluir para Loogamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_FANGMON', 'Fragmento do Fangmon', 'Fragmento para evoluir para Fangmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_ASTAMON', 'Fragmento do Astamon', 'Fragmento para evoluir para Astamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_BELPHEMONSLEEPMODE', 'Fragmento do Belphemon: Sleep Mode', 'Fragmento para evoluir para Belphemon: Sleep Mode.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_CHAPMON', 'Fragmento do Chapmon', 'Fragmento para evoluir para Chapmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_KAMEMON', 'Fragmento do Kamemon', 'Fragmento para evoluir para Kamemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_GAWAPPAMON', 'Fragmento do Gawappamon', 'Fragmento para evoluir para Gawappamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_GRAPLEOMON', 'Fragmento do GrapLeomon', 'Fragmento para evoluir para GrapLeomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_SABERLEOMON', 'Fragmento do SaberLeomon', 'Fragmento para evoluir para SaberLeomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_HOPMON', 'Fragmento do Hopmon', 'Fragmento para evoluir para Hopmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_BEARMON', 'Fragmento do Bearmon', 'Fragmento para evoluir para Bearmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_GRYZMON', 'Fragmento do Gryzmon', 'Fragmento para evoluir para Gryzmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_GRAPPULEOMON', 'Fragmento do Grappu Leomon', 'Fragmento para evoluir para Grappu Leomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_BANCHOLEOMON', 'Fragmento do BanchoLeomon', 'Fragmento para evoluir para BanchoLeomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_SUNMON', 'Fragmento do Sunmon', 'Fragmento para evoluir para Sunmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_CORONAMON', 'Fragmento do Coronamon', 'Fragmento para evoluir para Coronamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_FIRAMON', 'Fragmento do Firamon', 'Fragmento para evoluir para Firamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_FLAREMON', 'Fragmento do Flaremon', 'Fragmento para evoluir para Flaremon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_APOLLOMON', 'Fragmento do Apollomon', 'Fragmento para evoluir para Apollomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_BUDMON', 'Fragmento do Budmon', 'Fragmento para evoluir para Budmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_LALAMON', 'Fragmento do Lalamon', 'Fragmento para evoluir para Lalamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_SUNFLOWMON', 'Fragmento do Sunflowmon', 'Fragmento para evoluir para Sunflowmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_LILAMON', 'Fragmento do Lilamon', 'Fragmento para evoluir para Lilamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_ROSEMON', 'Fragmento do Rosemon', 'Fragmento para evoluir para Rosemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_KYAROMON', 'Fragmento do Kyaromon', 'Fragmento para evoluir para Kyaromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_GAOMON', 'Fragmento do Gaomon', 'Fragmento para evoluir para Gaomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_GAOGAMON', 'Fragmento do Gaogamon', 'Fragmento para evoluir para Gaogamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_MACHGAOGAMON', 'Fragmento do MachGaogamon', 'Fragmento para evoluir para MachGaogamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_MIRAGEGAOGAMON', 'Fragmento do MirageGaogamon', 'Fragmento para evoluir para MirageGaogamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_XIAOMON', 'Fragmento do Xiaomon', 'Fragmento para evoluir para Xiaomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_LABRAMON', 'Fragmento do Labramon', 'Fragmento para evoluir para Labramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_DOBERMON', 'Fragmento do Dobermon', 'Fragmento para evoluir para Dobermon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_CERBERUMON', 'Fragmento do Cerberumon', 'Fragmento para evoluir para Cerberumon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_PLUTOMON', 'Fragmento do Plutomon', 'Fragmento para evoluir para Plutomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_CANDMON', 'Fragmento do Candmon', 'Fragmento para evoluir para Candmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_CANDLEMON', 'Fragmento do Candlemon', 'Fragmento para evoluir para Candlemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_MERAMON', 'Fragmento do Meramon', 'Fragmento para evoluir para Meramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_SKULLMERAMON', 'Fragmento do SkullMeramon', 'Fragmento para evoluir para SkullMeramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_BOLTMON', 'Fragmento do Boltmon', 'Fragmento para evoluir para Boltmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_BABYDMON', 'Fragmento do Babydmon', 'Fragmento para evoluir para Babydmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_HACKMON', 'Fragmento do Hackmon', 'Fragmento para evoluir para Hackmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_BAOHACKMON', 'Fragmento do Bao Hackmon', 'Fragmento para evoluir para Bao Hackmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_SAVIORHACKMON', 'Fragmento do SaviorHackmon', 'Fragmento para evoluir para SaviorHackmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_JESMON', 'Fragmento do Jesmon', 'Fragmento para evoluir para Jesmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_FRIMON', 'Fragmento do Frimon', 'Fragmento para evoluir para Frimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_LUNAMON', 'Fragmento do Lunamon', 'Fragmento para evoluir para Lunamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_LEKISMON', 'Fragmento do Lekismon', 'Fragmento para evoluir para Lekismon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_CRESCEMON', 'Fragmento do Crescemon', 'Fragmento para evoluir para Crescemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_DIANAMON', 'Fragmento do Dianamon', 'Fragmento para evoluir para Dianamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_TUNOMON', 'Fragmento do Tunomon', 'Fragmento para evoluir para Tunomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_GANIMON', 'Fragmento do Ganimon', 'Fragmento para evoluir para Ganimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_HOOKMON', 'Fragmento do Hookmon', 'Fragmento para evoluir para Hookmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_MARINEDEVIMON', 'Fragmento do MarineDevimon', 'Fragmento para evoluir para MarineDevimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_PUKUMON', 'Fragmento do Pukumon', 'Fragmento para evoluir para Pukumon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_WANYAMON', 'Fragmento do Wanyamon', 'Fragmento para evoluir para Wanyamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_LIOLLMON', 'Fragmento do Liollmon', 'Fragmento para evoluir para Liollmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_LIAMON', 'Fragmento do Liamon', 'Fragmento para evoluir para Liamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_LOADERLIOMON', 'Fragmento do LoaderLiomon', 'Fragmento para evoluir para LoaderLiomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_HEAVYLEOMON', 'Fragmento do HeavyLeomon', 'Fragmento para evoluir para HeavyLeomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_PUROROMON', 'Fragmento do Puroromon', 'Fragmento para evoluir para Puroromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_FUNBEEMON', 'Fragmento do Funbeemon', 'Fragmento para evoluir para Funbeemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_WASPMON', 'Fragmento do Waspmon', 'Fragmento para evoluir para Waspmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_CANNONBEEMON', 'Fragmento do CannonBeemon', 'Fragmento para evoluir para CannonBeemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_TIGERVESPAMON', 'Fragmento do TigerVespamon', 'Fragmento para evoluir para TigerVespamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_POROMON', 'Fragmento do Poromon', 'Fragmento para evoluir para Poromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_HAWKMON', 'Fragmento do Hawkmon', 'Fragmento para evoluir para Hawkmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_AQUILAMON', 'Fragmento do Aquilamon', 'Fragmento para evoluir para Aquilamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_SILPHYMON', 'Fragmento do Silphymon', 'Fragmento para evoluir para Silphymon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_VALKYRIMON', 'Fragmento do Valkyrimon', 'Fragmento para evoluir para Valkyrimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_CUPIMON', 'Fragmento do Cupimon', 'Fragmento para evoluir para Cupimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_PLOTMON', 'Fragmento do Plotmon', 'Fragmento para evoluir para Plotmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_TAILMON', 'Fragmento do Tailmon', 'Fragmento para evoluir para Tailmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_ANGEWOMON', 'Fragmento do Angewomon', 'Fragmento para evoluir para Angewomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_OPHANIMON', 'Fragmento do Ophanimon', 'Fragmento para evoluir para Ophanimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_PINAMON', 'Fragmento do Pinamon', 'Fragmento para evoluir para Pinamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_POMUMON', 'Fragmento do Pomumon', 'Fragmento para evoluir para Pomumon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_PARASAURMON', 'Fragmento do Parasaurmon', 'Fragmento para evoluir para Parasaurmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_PARROTMON', 'Fragmento do Parrotmon', 'Fragmento para evoluir para Parrotmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_GRYPHONMON', 'Fragmento do Gryphonmon', 'Fragmento para evoluir para Gryphonmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_PUYOYOMON', 'Fragmento do Puyoyomon', 'Fragmento para evoluir para Puyoyomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_JELLYMON', 'Fragmento do Jellymon', 'Fragmento para evoluir para Jellymon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_TESLAJELLYMON', 'Fragmento do TeslaJellymon', 'Fragmento para evoluir para TeslaJellymon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_AMPHIMON', 'Fragmento do Amphimon', 'Fragmento para evoluir para Amphimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_CTHYLLAMON', 'Fragmento do Cthyllamon', 'Fragmento para evoluir para Cthyllamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_BOSAMON', 'Fragmento do Bosamon', 'Fragmento para evoluir para Bosamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_ANGORAMON', 'Fragmento do Angoramon', 'Fragmento para evoluir para Angoramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_SYMBAREANGORAMON', 'Fragmento do SymbareAngoramon', 'Fragmento para evoluir para SymbareAngoramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_LAMORTMON', 'Fragmento do Lamortmon', 'Fragmento para evoluir para Lamortmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_DIARBBITMON', 'Fragmento do Diarbbitmon', 'Fragmento para evoluir para Diarbbitmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_POKOMON', 'Fragmento do Pokomon', 'Fragmento para evoluir para Pokomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_RENAMON', 'Fragmento do Renamon', 'Fragmento para evoluir para Renamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_KYUBIMON', 'Fragmento do Kyubimon', 'Fragmento para evoluir para Kyubimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_TAOMON', 'Fragmento do Taomon', 'Fragmento para evoluir para Taomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_SAKUYAMON', 'Fragmento do Sakuyamon', 'Fragmento para evoluir para Sakuyamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_GOROMON', 'Fragmento do Goromon', 'Fragmento para evoluir para Goromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_SUNARIZAMON', 'Fragmento do Sunarizamon', 'Fragmento para evoluir para Sunarizamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_VERMILIMON', 'Fragmento do Vermilimon', 'Fragmento para evoluir para Vermilimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_SKULLGREYMON', 'Fragmento do SkullGreymon', 'Fragmento para evoluir para SkullGreymon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_EBONWUMON', 'Fragmento do Ebonwumon', 'Fragmento para evoluir para Ebonwumon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_MORPHOMON', 'Fragmento do Morphomon', 'Fragmento para evoluir para Morphomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_DOKUGUMON', 'Fragmento do Dokugumon', 'Fragmento para evoluir para Dokugumon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_OKUWAMON', 'Fragmento do Okuwamon', 'Fragmento para evoluir para Okuwamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_QUEENBEEMON', 'Fragmento do QueenBeemon', 'Fragmento para evoluir para QueenBeemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_KOTEMON', 'Fragmento do Kotemon', 'Fragmento para evoluir para Kotemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_GLADIMON', 'Fragmento do Gladimon', 'Fragmento para evoluir para Gladimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_KNIGHTMON', 'Fragmento do Knightmon', 'Fragmento para evoluir para Knightmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_CRANIUMMON', 'Fragmento do Craniummon', 'Fragmento para evoluir para Craniummon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_UPAMON', 'Fragmento do Upamon', 'Fragmento para evoluir para Upamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_ARMADIMON', 'Fragmento do Armadimon', 'Fragmento para evoluir para Armadimon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_ANKYLOMON', 'Fragmento do Ankylomon', 'Fragmento para evoluir para Ankylomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_TRICERAMON', 'Fragmento do Triceramon', 'Fragmento para evoluir para Triceramon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_RUSTTYRANNOMON', 'Fragmento do RustTyrannomon', 'Fragmento para evoluir para RustTyrannomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_FLUFFYMON', 'Fragmento do Fluffymon', 'Fragmento para evoluir para Fluffymon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 10, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_baby2'),
    ('FRAGMENT_PTEROMON', 'Fragmento do Pteromon', 'Fragmento para evoluir para Pteromon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_GALEMON', 'Fragmento do Galemon', 'Fragmento para evoluir para Galemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 60, TRUE, TRUE, FALSE, 999, 'RARE', 'fragment_champion_specific'),
    ('FRAGMENT_GRANDGALEMON', 'Fragmento do GrandGalemon', 'Fragmento para evoluir para GrandGalemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_ZEPHAGAMON', 'Fragmento do Zephagamon', 'Fragmento para evoluir para Zephagamon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific'),
    ('FRAGMENT_GHOSTMON', 'Fragmento do Ghostmon', 'Fragmento para evoluir para Ghostmon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 25, TRUE, TRUE, FALSE, 999, 'COMMON', 'fragment_rookie_specific'),
    ('FRAGMENT_PHANTOMON', 'Fragmento do Phantomon', 'Fragmento para evoluir para Phantomon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 120, TRUE, TRUE, FALSE, 999, 'EPIC', 'fragment_ultimate_specific'),
    ('FRAGMENT_PIEMON', 'Fragmento do Piemon', 'Fragmento para evoluir para Piemon.', 'EVOLUTION_MATERIAL', TRUE, NULL, 250, FALSE, TRUE, FALSE, 999, 'LEGENDARY', 'fragment_mega_specific')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    stackable = EXCLUDED.stackable,
    sell_price = EXCLUDED.sell_price,
    tradable = EXCLUDED.tradable,
    sellable = EXCLUDED.sellable,
    usable = EXCLUDED.usable,
    max_stack = EXCLUDED.max_stack,
    rarity = EXCLUDED.rarity,
    icon = EXCLUDED.icon;
