BEGIN;

-- 9 baús por set e 10 baús por tier. Cada abertura concede exatamente um equipamento.
-- A raridade da instância é herdada do template quando equipment_rarity é NULL.

INSERT INTO loot_tables (code, name, description, active) VALUES
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Baú do Set Balanced', 'Contém um equipamento aleatório do set Balanced, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Baú do Set Berserker', 'Contém um equipamento aleatório do set Berserker, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Baú do Set Data Breaker', 'Contém um equipamento aleatório do set Data Breaker, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Baú do Set Firewall', 'Contém um equipamento aleatório do set Firewall, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Baú do Set Guardian', 'Contém um equipamento aleatório do set Guardian, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Baú do Set Kernel', 'Contém um equipamento aleatório do set Kernel, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Baú do Set Overclock', 'Contém um equipamento aleatório do set Overclock, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Baú do Set Overlord', 'Contém um equipamento aleatório do set Overlord, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Baú do Set Vitality', 'Contém um equipamento aleatório do set Vitality, entre os tiers T1 e T10.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Baú do Tier T1', 'Contém um equipamento aleatório de tier T1 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Baú do Tier T2', 'Contém um equipamento aleatório de tier T2 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Baú do Tier T3', 'Contém um equipamento aleatório de tier T3 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Baú do Tier T4', 'Contém um equipamento aleatório de tier T4 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Baú do Tier T5', 'Contém um equipamento aleatório de tier T5 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Baú do Tier T6', 'Contém um equipamento aleatório de tier T6 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Baú do Tier T7', 'Contém um equipamento aleatório de tier T7 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Baú do Tier T8', 'Contém um equipamento aleatório de tier T8 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Baú do Tier T9', 'Contém um equipamento aleatório de tier T9 entre todos os sets disponíveis.', TRUE),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Baú do Tier T10', 'Contém um equipamento aleatório de tier T10 entre todos os sets disponíveis.', TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, active = EXCLUDED.active;

INSERT INTO loot_table_rarity_weights (loot_table_id, rarity, weight)
SELECT lt.id, weights.rarity, weights.weight
FROM loot_tables lt CROSS JOIN (VALUES ('COMMON', 100), ('RARE', 1), ('EPIC', 1), ('LEGENDARY', 1)) AS weights(rarity, weight)
WHERE lt.code LIKE 'LOOT_TABLE_EQUIPMENT_%'
ON CONFLICT (loot_table_id, rarity) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO loot_table_entries (loot_table_id, rarity, item_type, material_code, equipment_template_name, equipment_rarity, weight, min_quantity, max_quantity, active)
SELECT lt.id, 'COMMON', 'EQUIPMENT', NULL, template.name, NULL, 1, 1, 1, TRUE
FROM loot_tables lt
JOIN (VALUES
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Armadura do Equilíbrio T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Lâmina do Equilíbrio T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_BALANCED', 'Símbolo do Equilíbrio T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Couraça Berserker T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Emblema Berserker T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_BERSERKER', 'Garra Berserker T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Couraça Data Breaker T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Fragmento Data Breaker T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER', 'Garra Data Breaker T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Couraça Firewall T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Lança Firewall T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_FIREWALL', 'Núcleo Firewall T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Armadura Guardiã T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Lança Guardiã T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_GUARDIAN', 'Medalha Guardiã T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Core T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Kernel Shell T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_KERNEL', 'Martelo Kernel T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Chip Overclock T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Frame Overclock T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK', 'Lâmina Overclock T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Coroa do Overlord T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Couraça do Overlord T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_OVERLORD', 'Lâmina do Overlord T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T1'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T2'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T3'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T4'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T5'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T6'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T7'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T8'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T9'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Cetro da Vitalidade T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Emblema da Vitalidade T10'),
    ('LOOT_TABLE_EQUIPMENT_SET_VITALITY', 'Vestes da Vitalidade T10')
 ) AS template(loot_table_code, name) ON template.loot_table_code = lt.code
WHERE lt.code LIKE 'LOOT_TABLE_EQUIPMENT_SET_%'
  AND NOT EXISTS (SELECT 1 FROM loot_table_entries entry WHERE entry.loot_table_id = lt.id AND entry.item_type = 'EQUIPMENT' AND entry.equipment_template_name = template.name);

INSERT INTO loot_table_entries (loot_table_id, rarity, item_type, material_code, equipment_template_name, equipment_rarity, weight, min_quantity, max_quantity, active)
SELECT lt.id, 'COMMON', 'EQUIPMENT', NULL, template.name, NULL, 1, 1, 1, TRUE
FROM loot_tables lt
JOIN (VALUES
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Armadura do Equilíbrio T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Lâmina do Equilíbrio T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Símbolo do Equilíbrio T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Armadura do Equilíbrio T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Lâmina do Equilíbrio T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Símbolo do Equilíbrio T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Armadura do Equilíbrio T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Lâmina do Equilíbrio T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Símbolo do Equilíbrio T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Armadura do Equilíbrio T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Lâmina do Equilíbrio T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Símbolo do Equilíbrio T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Armadura do Equilíbrio T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Lâmina do Equilíbrio T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Símbolo do Equilíbrio T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Armadura do Equilíbrio T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Lâmina do Equilíbrio T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Símbolo do Equilíbrio T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Armadura do Equilíbrio T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Lâmina do Equilíbrio T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Símbolo do Equilíbrio T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Armadura do Equilíbrio T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Lâmina do Equilíbrio T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Símbolo do Equilíbrio T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Armadura do Equilíbrio T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Lâmina do Equilíbrio T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Símbolo do Equilíbrio T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Armadura do Equilíbrio T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Lâmina do Equilíbrio T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Símbolo do Equilíbrio T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Couraça Berserker T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Emblema Berserker T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Garra Berserker T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Couraça Berserker T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Emblema Berserker T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Garra Berserker T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Couraça Berserker T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Emblema Berserker T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Garra Berserker T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Couraça Berserker T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Emblema Berserker T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Garra Berserker T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Couraça Berserker T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Emblema Berserker T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Garra Berserker T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Couraça Berserker T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Emblema Berserker T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Garra Berserker T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Couraça Berserker T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Emblema Berserker T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Garra Berserker T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Couraça Berserker T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Emblema Berserker T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Garra Berserker T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Couraça Berserker T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Emblema Berserker T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Garra Berserker T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Couraça Berserker T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Emblema Berserker T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Garra Berserker T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Couraça Data Breaker T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Fragmento Data Breaker T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Garra Data Breaker T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Couraça Data Breaker T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Fragmento Data Breaker T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Garra Data Breaker T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Couraça Data Breaker T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Fragmento Data Breaker T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Garra Data Breaker T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Couraça Data Breaker T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Fragmento Data Breaker T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Garra Data Breaker T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Couraça Data Breaker T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Fragmento Data Breaker T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Garra Data Breaker T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Couraça Data Breaker T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Fragmento Data Breaker T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Garra Data Breaker T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Couraça Data Breaker T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Fragmento Data Breaker T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Garra Data Breaker T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Couraça Data Breaker T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Fragmento Data Breaker T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Garra Data Breaker T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Couraça Data Breaker T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Fragmento Data Breaker T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Garra Data Breaker T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Couraça Data Breaker T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Fragmento Data Breaker T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Garra Data Breaker T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Couraça Firewall T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Lança Firewall T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Núcleo Firewall T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Couraça Firewall T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Lança Firewall T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Núcleo Firewall T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Couraça Firewall T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Lança Firewall T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Núcleo Firewall T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Couraça Firewall T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Lança Firewall T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Núcleo Firewall T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Couraça Firewall T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Lança Firewall T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Núcleo Firewall T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Couraça Firewall T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Lança Firewall T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Núcleo Firewall T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Couraça Firewall T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Lança Firewall T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Núcleo Firewall T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Couraça Firewall T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Lança Firewall T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Núcleo Firewall T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Couraça Firewall T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Lança Firewall T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Núcleo Firewall T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Couraça Firewall T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Lança Firewall T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Núcleo Firewall T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Armadura Guardiã T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Lança Guardiã T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Medalha Guardiã T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Armadura Guardiã T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Lança Guardiã T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Medalha Guardiã T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Armadura Guardiã T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Lança Guardiã T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Medalha Guardiã T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Armadura Guardiã T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Lança Guardiã T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Medalha Guardiã T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Armadura Guardiã T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Lança Guardiã T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Medalha Guardiã T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Armadura Guardiã T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Lança Guardiã T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Medalha Guardiã T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Armadura Guardiã T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Lança Guardiã T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Medalha Guardiã T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Armadura Guardiã T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Lança Guardiã T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Medalha Guardiã T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Armadura Guardiã T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Lança Guardiã T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Medalha Guardiã T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Armadura Guardiã T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Lança Guardiã T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Medalha Guardiã T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Kernel Core T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Kernel Shell T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Martelo Kernel T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Kernel Core T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Kernel Shell T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Martelo Kernel T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Kernel Core T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Kernel Shell T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Martelo Kernel T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Kernel Core T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Kernel Shell T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Martelo Kernel T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Kernel Core T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Kernel Shell T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Martelo Kernel T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Kernel Core T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Kernel Shell T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Martelo Kernel T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Kernel Core T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Kernel Shell T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Martelo Kernel T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Kernel Core T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Kernel Shell T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Martelo Kernel T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Kernel Core T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Kernel Shell T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Martelo Kernel T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Kernel Core T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Kernel Shell T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Martelo Kernel T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Chip Overclock T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Frame Overclock T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Lâmina Overclock T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Chip Overclock T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Frame Overclock T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Lâmina Overclock T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Chip Overclock T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Frame Overclock T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Lâmina Overclock T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Chip Overclock T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Frame Overclock T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Lâmina Overclock T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Chip Overclock T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Frame Overclock T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Lâmina Overclock T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Chip Overclock T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Frame Overclock T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Lâmina Overclock T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Chip Overclock T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Frame Overclock T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Lâmina Overclock T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Chip Overclock T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Frame Overclock T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Lâmina Overclock T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Chip Overclock T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Frame Overclock T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Lâmina Overclock T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Chip Overclock T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Frame Overclock T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Lâmina Overclock T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Coroa do Overlord T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Couraça do Overlord T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Lâmina do Overlord T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Coroa do Overlord T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Couraça do Overlord T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Lâmina do Overlord T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Coroa do Overlord T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Couraça do Overlord T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Lâmina do Overlord T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Coroa do Overlord T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Couraça do Overlord T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Lâmina do Overlord T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Coroa do Overlord T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Couraça do Overlord T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Lâmina do Overlord T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Coroa do Overlord T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Couraça do Overlord T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Lâmina do Overlord T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Coroa do Overlord T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Couraça do Overlord T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Lâmina do Overlord T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Coroa do Overlord T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Couraça do Overlord T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Lâmina do Overlord T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Coroa do Overlord T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Couraça do Overlord T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Lâmina do Overlord T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Coroa do Overlord T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Couraça do Overlord T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Lâmina do Overlord T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Cetro da Vitalidade T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Emblema da Vitalidade T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T1', 'Vestes da Vitalidade T1'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Cetro da Vitalidade T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Emblema da Vitalidade T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T2', 'Vestes da Vitalidade T2'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Cetro da Vitalidade T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Emblema da Vitalidade T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T3', 'Vestes da Vitalidade T3'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Cetro da Vitalidade T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Emblema da Vitalidade T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T4', 'Vestes da Vitalidade T4'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Cetro da Vitalidade T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Emblema da Vitalidade T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T5', 'Vestes da Vitalidade T5'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Cetro da Vitalidade T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Emblema da Vitalidade T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T6', 'Vestes da Vitalidade T6'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Cetro da Vitalidade T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Emblema da Vitalidade T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T7', 'Vestes da Vitalidade T7'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Cetro da Vitalidade T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Emblema da Vitalidade T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T8', 'Vestes da Vitalidade T8'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Cetro da Vitalidade T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Emblema da Vitalidade T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T9', 'Vestes da Vitalidade T9'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Cetro da Vitalidade T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Emblema da Vitalidade T10'),
    ('LOOT_TABLE_EQUIPMENT_TIER_T10', 'Vestes da Vitalidade T10')
 ) AS template(loot_table_code, name) ON template.loot_table_code = lt.code
WHERE lt.code LIKE 'LOOT_TABLE_EQUIPMENT_TIER_%'
  AND NOT EXISTS (SELECT 1 FROM loot_table_entries entry WHERE entry.loot_table_id = lt.id AND entry.item_type = 'EQUIPMENT' AND entry.equipment_template_name = template.name);

INSERT INTO item_definitions (code, name, description, category, stackable, buy_price, sell_price, tradable, sellable, usable, max_stack, rarity, icon) VALUES
    ('CHEST_EQUIPMENT_SET_BALANCED', 'Baú do Set Balanced', 'Baú que contém um equipamento aleatório do set Balanced.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_balanced'),
    ('CHEST_EQUIPMENT_SET_BERSERKER', 'Baú do Set Berserker', 'Baú que contém um equipamento aleatório do set Berserker.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_berserker'),
    ('CHEST_EQUIPMENT_SET_DATA_BREAKER', 'Baú do Set Data Breaker', 'Baú que contém um equipamento aleatório do set Data Breaker.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_data_breaker'),
    ('CHEST_EQUIPMENT_SET_FIREWALL', 'Baú do Set Firewall', 'Baú que contém um equipamento aleatório do set Firewall.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_firewall'),
    ('CHEST_EQUIPMENT_SET_GUARDIAN', 'Baú do Set Guardian', 'Baú que contém um equipamento aleatório do set Guardian.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_guardian'),
    ('CHEST_EQUIPMENT_SET_KERNEL', 'Baú do Set Kernel', 'Baú que contém um equipamento aleatório do set Kernel.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_kernel'),
    ('CHEST_EQUIPMENT_SET_OVERCLOCK', 'Baú do Set Overclock', 'Baú que contém um equipamento aleatório do set Overclock.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_overclock'),
    ('CHEST_EQUIPMENT_SET_OVERLORD', 'Baú do Set Overlord', 'Baú que contém um equipamento aleatório do set Overlord.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_overlord'),
    ('CHEST_EQUIPMENT_SET_VITALITY', 'Baú do Set Vitality', 'Baú que contém um equipamento aleatório do set Vitality.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_set_vitality'),
    ('CHEST_EQUIPMENT_TIER_T1', 'Baú do Tier T1', 'Baú que contém um equipamento aleatório de tier T1 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t1'),
    ('CHEST_EQUIPMENT_TIER_T2', 'Baú do Tier T2', 'Baú que contém um equipamento aleatório de tier T2 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t2'),
    ('CHEST_EQUIPMENT_TIER_T3', 'Baú do Tier T3', 'Baú que contém um equipamento aleatório de tier T3 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t3'),
    ('CHEST_EQUIPMENT_TIER_T4', 'Baú do Tier T4', 'Baú que contém um equipamento aleatório de tier T4 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t4'),
    ('CHEST_EQUIPMENT_TIER_T5', 'Baú do Tier T5', 'Baú que contém um equipamento aleatório de tier T5 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t5'),
    ('CHEST_EQUIPMENT_TIER_T6', 'Baú do Tier T6', 'Baú que contém um equipamento aleatório de tier T6 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t6'),
    ('CHEST_EQUIPMENT_TIER_T7', 'Baú do Tier T7', 'Baú que contém um equipamento aleatório de tier T7 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t7'),
    ('CHEST_EQUIPMENT_TIER_T8', 'Baú do Tier T8', 'Baú que contém um equipamento aleatório de tier T8 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t8'),
    ('CHEST_EQUIPMENT_TIER_T9', 'Baú do Tier T9', 'Baú que contém um equipamento aleatório de tier T9 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t9'),
    ('CHEST_EQUIPMENT_TIER_T10', 'Baú do Tier T10', 'Baú que contém um equipamento aleatório de tier T10 entre todos os sets.', 'CHEST', TRUE, NULL, NULL, TRUE, TRUE, TRUE, 999, 'COMMON', 'chest_equipment_tier_t10')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, category = EXCLUDED.category, stackable = EXCLUDED.stackable, tradable = EXCLUDED.tradable, sellable = EXCLUDED.sellable, usable = EXCLUDED.usable, max_stack = EXCLUDED.max_stack, rarity = EXCLUDED.rarity, icon = EXCLUDED.icon;

INSERT INTO chest_definitions (code, name, description, icon, loot_table_id, item_definition_id, tradable, active)
SELECT source.code, source.name, source.description, source.icon, lt.id, item.id, TRUE, TRUE
FROM (VALUES
    ('CHEST_EQUIPMENT_SET_BALANCED', 'Baú do Set Balanced', 'Baú que contém um equipamento aleatório do set Balanced.', 'chest_equipment_set_balanced', 'LOOT_TABLE_EQUIPMENT_SET_BALANCED'),
    ('CHEST_EQUIPMENT_SET_BERSERKER', 'Baú do Set Berserker', 'Baú que contém um equipamento aleatório do set Berserker.', 'chest_equipment_set_berserker', 'LOOT_TABLE_EQUIPMENT_SET_BERSERKER'),
    ('CHEST_EQUIPMENT_SET_DATA_BREAKER', 'Baú do Set Data Breaker', 'Baú que contém um equipamento aleatório do set Data Breaker.', 'chest_equipment_set_data_breaker', 'LOOT_TABLE_EQUIPMENT_SET_DATA_BREAKER'),
    ('CHEST_EQUIPMENT_SET_FIREWALL', 'Baú do Set Firewall', 'Baú que contém um equipamento aleatório do set Firewall.', 'chest_equipment_set_firewall', 'LOOT_TABLE_EQUIPMENT_SET_FIREWALL'),
    ('CHEST_EQUIPMENT_SET_GUARDIAN', 'Baú do Set Guardian', 'Baú que contém um equipamento aleatório do set Guardian.', 'chest_equipment_set_guardian', 'LOOT_TABLE_EQUIPMENT_SET_GUARDIAN'),
    ('CHEST_EQUIPMENT_SET_KERNEL', 'Baú do Set Kernel', 'Baú que contém um equipamento aleatório do set Kernel.', 'chest_equipment_set_kernel', 'LOOT_TABLE_EQUIPMENT_SET_KERNEL'),
    ('CHEST_EQUIPMENT_SET_OVERCLOCK', 'Baú do Set Overclock', 'Baú que contém um equipamento aleatório do set Overclock.', 'chest_equipment_set_overclock', 'LOOT_TABLE_EQUIPMENT_SET_OVERCLOCK'),
    ('CHEST_EQUIPMENT_SET_OVERLORD', 'Baú do Set Overlord', 'Baú que contém um equipamento aleatório do set Overlord.', 'chest_equipment_set_overlord', 'LOOT_TABLE_EQUIPMENT_SET_OVERLORD'),
    ('CHEST_EQUIPMENT_SET_VITALITY', 'Baú do Set Vitality', 'Baú que contém um equipamento aleatório do set Vitality.', 'chest_equipment_set_vitality', 'LOOT_TABLE_EQUIPMENT_SET_VITALITY'),
    ('CHEST_EQUIPMENT_TIER_T1', 'Baú do Tier T1', 'Baú que contém um equipamento aleatório de tier T1 entre todos os sets.', 'chest_equipment_tier_t1', 'LOOT_TABLE_EQUIPMENT_TIER_T1'),
    ('CHEST_EQUIPMENT_TIER_T2', 'Baú do Tier T2', 'Baú que contém um equipamento aleatório de tier T2 entre todos os sets.', 'chest_equipment_tier_t2', 'LOOT_TABLE_EQUIPMENT_TIER_T2'),
    ('CHEST_EQUIPMENT_TIER_T3', 'Baú do Tier T3', 'Baú que contém um equipamento aleatório de tier T3 entre todos os sets.', 'chest_equipment_tier_t3', 'LOOT_TABLE_EQUIPMENT_TIER_T3'),
    ('CHEST_EQUIPMENT_TIER_T4', 'Baú do Tier T4', 'Baú que contém um equipamento aleatório de tier T4 entre todos os sets.', 'chest_equipment_tier_t4', 'LOOT_TABLE_EQUIPMENT_TIER_T4'),
    ('CHEST_EQUIPMENT_TIER_T5', 'Baú do Tier T5', 'Baú que contém um equipamento aleatório de tier T5 entre todos os sets.', 'chest_equipment_tier_t5', 'LOOT_TABLE_EQUIPMENT_TIER_T5'),
    ('CHEST_EQUIPMENT_TIER_T6', 'Baú do Tier T6', 'Baú que contém um equipamento aleatório de tier T6 entre todos os sets.', 'chest_equipment_tier_t6', 'LOOT_TABLE_EQUIPMENT_TIER_T6'),
    ('CHEST_EQUIPMENT_TIER_T7', 'Baú do Tier T7', 'Baú que contém um equipamento aleatório de tier T7 entre todos os sets.', 'chest_equipment_tier_t7', 'LOOT_TABLE_EQUIPMENT_TIER_T7'),
    ('CHEST_EQUIPMENT_TIER_T8', 'Baú do Tier T8', 'Baú que contém um equipamento aleatório de tier T8 entre todos os sets.', 'chest_equipment_tier_t8', 'LOOT_TABLE_EQUIPMENT_TIER_T8'),
    ('CHEST_EQUIPMENT_TIER_T9', 'Baú do Tier T9', 'Baú que contém um equipamento aleatório de tier T9 entre todos os sets.', 'chest_equipment_tier_t9', 'LOOT_TABLE_EQUIPMENT_TIER_T9'),
    ('CHEST_EQUIPMENT_TIER_T10', 'Baú do Tier T10', 'Baú que contém um equipamento aleatório de tier T10 entre todos os sets.', 'chest_equipment_tier_t10', 'LOOT_TABLE_EQUIPMENT_TIER_T10')
 ) AS source(code, name, description, icon, loot_table_code)
JOIN loot_tables lt ON lt.code = source.loot_table_code
JOIN item_definitions item ON item.code = source.code
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, icon = EXCLUDED.icon, loot_table_id = EXCLUDED.loot_table_id, item_definition_id = EXCLUDED.item_definition_id, tradable = EXCLUDED.tradable, active = EXCLUDED.active;

DO $$
DECLARE set_chests INTEGER; tier_chests INTEGER; set_entries INTEGER; tier_entries INTEGER;
BEGIN
    SELECT COUNT(*) INTO set_chests FROM chest_definitions WHERE code LIKE 'CHEST_EQUIPMENT_SET_%';
    SELECT COUNT(*) INTO tier_chests FROM chest_definitions WHERE code LIKE 'CHEST_EQUIPMENT_TIER_%';
    SELECT COUNT(*) INTO set_entries FROM loot_table_entries entry JOIN loot_tables lt ON lt.id = entry.loot_table_id WHERE lt.code LIKE 'LOOT_TABLE_EQUIPMENT_SET_%';
    SELECT COUNT(*) INTO tier_entries FROM loot_table_entries entry JOIN loot_tables lt ON lt.id = entry.loot_table_id WHERE lt.code LIKE 'LOOT_TABLE_EQUIPMENT_TIER_%';
    IF set_chests <> 9 OR tier_chests <> 10 OR set_entries <> 270 OR tier_entries <> 270 THEN
        RAISE EXCEPTION 'Equipment chest seed mismatch: set chests %, tier chests %, set entries %, tier entries %', set_chests, tier_chests, set_entries, tier_entries;
    END IF;
END $$;
COMMIT;
