ALTER TABLE mission_definitions
    ADD COLUMN created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN created_by  VARCHAR(80) NOT NULL DEFAULT 'system',
    ADD COLUMN updated_by  VARCHAR(80) NOT NULL DEFAULT 'system';
