spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mongodb:
    uri: ${SPRING_MONGODB_URI}

logging:
  level:
    org.springframework.jdbc: INFO

dro:
  app-version: ${DRO_APP_VERSION:0.0.1-SNAPSHOT}
  gameplay:
    energy:
      consumption-enabled: ${DRO_ENERGY_CONSUMPTION_ENABLED:true}

  registration:
    invite-required: true

  cors:
    allowed-origins: ${DRO_ALLOWED_ORIGINS}

  security:
    jwt:
      secret: ${DRO_JWT_SECRET}