spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dro_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:arisco2017}

  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://127.0.0.1:27017/dro_audit}

logging:
  level:
    org.springframework.jdbc: DEBUG

dro:
  app-version: ${DRO_APP_VERSION:0.0.1-SNAPSHOT}
  gameplay:
    energy:
      consumption-enabled: ${DRO_ENERGY_CONSUMPTION_ENABLED:true}

  registration:
    invite-required: ${DRO_REGISTRATION_INVITE_REQUIRED:false}

  cors:
    allowed-origins: ${DRO_ALLOWED_ORIGINS:http://localhost:8080,http://localhost:3000,http://localhost:27017,http://127.0.0.1:5500,http://127.0.0.1:59527}

  security:
    jwt:
      secret: ${DRO_JWT_SECRET:dro-local-development-secret-change-this-before-production-2026}