spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mongodb:
    uri: ${SPRING_MONGODB_URI}

logging:
  level:
    org.springframework.jdbc: INFO

dro:
  app-version: ${DRO_APP_VERSION:0.0.1-SNAPSHOT}
  gameplay:
    auto-boss-respawn-after-defeat-enabled: true
    boss-cooldown-enabled: ${DRO_BOSS_COOLDOWN_ENABLED:true}

    clan-raid:
      cooldown-enabled: ${DRO_CLAN_RAID_COOLDOWN_ENABLED:true}
      daily-attack-limit: ${DRO_CLAN_RAID_DAILY_ATTACK_LIMIT:99}

    energy:
      consumption-enabled: ${DRO_ENERGY_CONSUMPTION_ENABLED:false}

    arena:
      daily-challenge-limit: ${DRO_ARENA_DAILY_CHALLENGE_LIMIT:100}

    world-boss:
      cooldown-enabled: ${DRO_WORLD_BOSS_COOLDOWN_ENABLED:true}
      daily-attack-limit: ${DRO_WORLD_BOSS_DAILY_ATTACK_LIMIT:100}

  registration:
    invite-required: true

  cors:
    allowed-origins: ${DRO_ALLOWED_ORIGINS}

  security:
    jwt:
      secret: ${DRO_JWT_SECRET}